#################################################################
## This Makefile Exported by MinGW Developer Studio
## Copyright (c) 2002-2004 by Parinya Thipchart
#################################################################

PROJECT = use_tux_driver
CC = "E:\MinGWStudio\MinGW\bin\gcc.exe"
OBJ_DIR = ..\obj
OUTPUT_DIR = ..\test
TARGET = use_tux_driver.exe
C_INCLUDE_DIRS = 
C_PREPROC = 
CFLAGS = -pipe  -Wall -g2 -O0 
RC_INCLUDE_DIRS = 
RC_PREPROC = 
RCFLAGS = 
LIB_DIRS = -L "../win32"
LIBS = -ltuxdriver
LDFLAGS = -pipe 

ifeq ($(OS),Windows_NT)
  NULL =
else
  NULL = nul
endif

SRC_OBJS = \
  $(OBJ_DIR)/main.o

define build_target
@echo Linking...
@$(CC) -o "$(OUTPUT_DIR)\$(TARGET)" $(SRC_OBJS) $(LIB_DIRS) $(LIBS) $(LDFLAGS)
endef

define compile_source
@echo Compiling $<
@$(CC) $(CFLAGS) $(C_PREPROC) $(C_INCLUDE_DIRS) -c "$<" -o "$@"
endef

.PHONY: print_header directories

$(TARGET): print_header directories $(SRC_OBJS)
	$(build_target)

.PHONY: clean cleanall

cleanall:
	@echo Deleting intermediate files for 'use_tux_driver'
	-@del $(OBJ_DIR)\*.o
	-@del "$(OUTPUT_DIR)\$(TARGET)"
	-@rmdir "$(OUTPUT_DIR)"

clean:
	@echo Deleting intermediate files for 'use_tux_driver'
	-@del $(OBJ_DIR)\*.o

print_header:
	@echo ----------Configuration: use_tux_driver----------

directories:
	-@if not exist "$(OUTPUT_DIR)\$(NULL)" mkdir "$(OUTPUT_DIR)"
	-@if not exist "$(OBJ_DIR)\$(NULL)" mkdir "$(OBJ_DIR)"

$(OBJ_DIR)/main.o: main.c	\
../include/tux_driver.h
	$(compile_source)

