#################################################################
## This Makefile Exported by MinGW Developer Studio
## Copyright (c) 2005 by Parinya Thipchart
#################################################################
PROJECT = test_tux_driver
CC = "/usr/bin/gcc"
OBJ_DIR = ../obj
OUTPUT_DIR = ../test
TARGET = use_tux_driver
C_INCLUDE_DIRS =
C_PREPROC =
CFLAGS = -pipe  -Wall -g2 -O0
LIB_DIRS = -L ../unix
LIBS = -ldl -ltuxdriver -lm -lpthread
LDFLAGS = -pipe -static

SRC_OBJS = \
  $(OBJ_DIR)/main.o


define build_target
@echo Linking...
@$(CC) -o "$(OUTPUT_DIR)/$(TARGET)" $(SRC_OBJS) $(LIB_DIRS) $(LIBS) $(LDFLAGS)
endef

define compile_source
@echo Compiling $<
@$(CC) $(CFLAGS) $(C_PREPROC) $(C_INCLUDE_DIRS) -c "$<" -o "$@"
endef

.PHONY: print_header directories

$(TARGET): print_header directories $(SRC_OBJS)
	$(build_target)

.PHONY: clean cleanall

cleanall:
	@echo Deleting intermediate files for 'test_tux_driver'
	-@rm -rf "$(OBJ_DIR)"
	-@rm -rf "$(OUTPUT_DIR)/$(TARGET)"
	-@rmdir "$(OUTPUT_DIR)"

clean:
	@echo Deleting intermediate files for 'test_tux_driver'
	-@rm -rf "$(OBJ_DIR)"

print_header:
	@echo ----------Configuration: test_tux_driver----------

directories:
	-@if [ ! -d "$(OUTPUT_DIR)" ]; then mkdir "$(OUTPUT_DIR)"; fi
	-@if [ ! -d "$(OBJ_DIR)" ]; then mkdir "$(OBJ_DIR)"; fi

$(OBJ_DIR)/main.o: main.c	\
../include/tux_driver.h
	$(compile_source)



